server:
  # 端口号
  port: 8888
  servlet:
    context-path: /demo
  # 错误页，指定发生错误时，跳转的URL
  error:
    path: /error
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 200

spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_power?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    max-idle: 100
    max-wait: 10000
    min-idle: 50
    initial-size: 50
  thymeleaf:
    # 模板缓存
    cache: false
    # 模板前缀
    prefix: classpath:/templates/
    # 模板后缀
    suffix: .html
  # rabbitmq
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    listener:
#      simple:
#        # 消费者数量
#        concurrency: 10
#        max-concurrency: 10
#        # 每次从队列取几条数据
#        prefetch: 1
#        # 消费者自动启动
#        auto-startup: true
#        # 消费失败 重新加入队列
#        default-requeue-rejected: true
#    template:
#      retry:
#        # 重试
#        enabled: true
#        # 重试时间间隔
#        initial-interval: 1000
#        # 最大重试次数
#        max-attempts: 3
#        max-interval: 10000
#        multiplier: 1.0
  # 项目编码管理
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  # 添加static作为前缀才能访问
  mvc:
    static-path-pattern: /static/**
  # 配置静态资源路径
  resources:
    static-locations: file:${web.upload-path}
  # 日期返回默认格式 （不能存在带@EnableWebMvc注解的配置类，否则日期转换会失效）
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# redis配置
redis:
  hostip: 127.0.0.1
  port: 6379
  password: root
  timeout: 3
  poolMaxTotal: 500
  poolMaxIdle: 100
  poolMaxWait: 3


# 上传文件大小设置
multipart:
  enabled: true
  max-file-size: 50mb
  max-request-size: 50mb

# JWT编码
base64Security: 1abc$def2.TEZ

# windows静态资源路径
web.upload-path: D:/javaapp/upload/
# linux静态资源路径
# web.upload-path: /home/wsd/

web.upload-domain: http://127.0.0.1:8080/

# 日志
logging:
  config: classpath:mybatis/config/logback-core.xml
