server:
  # 端口号
  port: 8888
  servlet:
    context-path: /demo
  # 错误页，指定发生错误时，跳转的URL
  error:
    path: /error
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 150

spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_power?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  redis:
    # 数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    jedis:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        # 最大空闲
        max-idle: 8
        # 最小空闲
        min-idle: 0
    # 连接超时时间
    timeout: 10000

  # 项目编码管理
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  # 添加static作为前缀才能访问
  mvc:
    static-path-pattern: /static/**
  # 配置静态资源路径
  resources:
    static-locations: file:${web.upload-path}
  # 日期返回默认格式 （不能存在带@EnableWebMvc注解的配置类，否则日期转换会失效）
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# redis配置
redis:
  maxTotal: 50
  hostip: 127.0.0.1
  port: 6379
  password: root

# 上传文件大小设置
multipart:
  enabled: true
  max-file-size: 50mb
  max-request-size: 50mb

# JWT编码
base64Security: 1abc$def2.TEZ

# windows静态资源路径
web.upload-path: D:/javaapp/upload/
# linux静态资源路径
# web.upload-path: /home/wsd/

web.upload-domain: http://127.0.0.1:8080/

# 日志
#logging:
#  config: classpath:/mybatis/config/logback-core.xml
